about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(
        template_name='about/author.html'), name='author'),
    path('tech/', views.AboutTechView.as_view(
        template_name='about/tech.html'), name='tech'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path(
        'follow/',
        views.follow_index,
        name='follow_index'
    ),
    path('new/', views.new_post, name='new_post'),
    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/<int:post_id>/', views.post_view, name='post_view'),
    path(
        '<str:username>/<int:post_id>/edit/',
        views.post_edit,
        name='post_edit'
    ),
    path(
        '<str:username>/<int:post_id>/comment',
        views.add_comment,
        name='add_comment'
    ),
    path(
        '<str:username>/follow/',
        views.profile_follow,
        name="profile_follow"
    ),
    path(
        '<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("signup/", views.SignUp.as_view(), name="signup")
]

yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import handler404, handler500
from django.conf import settings
from django.conf.urls.static import static
from posts import views

handler404 = "posts.views.page_not_found"  # noqa
handler500 = "posts.views.server_error"  # noqa

urlpatterns = [
    path("auth/", include("users.urls")),

    path("500/", views.server_error, name="500"),

    path("404/", views.page_not_found, name="404"),

    path("auth/", include("django.contrib.auth.urls")),

    path("admin/", admin.site.urls),

    path("", include("posts.urls", namespace='posts')),

    path('about/', include('about.urls', namespace='about')),

]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        'Название сообщества', max_length=200,
        help_text='Название твоего сообщества'
    )
    slug = models.SlugField('Пометка', unique=True, help_text='Твоя пометка')
    description = models.TextField(
        'Описание сообщества', help_text='Расскажи о своём сообществе'
    )

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста', help_text='Напиши о чем думаешь')
    pub_date = models.DateTimeField(
        verbose_name='Дата публикации', auto_now_add=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='posts',
        verbose_name='Автор поста')
    group = models.ForeignKey(
        Group, on_delete=models.SET_NULL, related_name='posts',
        blank=True, null=True, verbose_name='Группа',
        help_text='Выбери группу')
    image = models.ImageField(
        upload_to='posts/', blank=True, null=True)

    def __str__(self):
        return self.text

    class Meta:
        ordering = ['-pub_date']


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.SET_NULL, null=True, related_name='comments')
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='comments')
    text = models.TextField(verbose_name='Коммент')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

    class Meta:
        ordering = ['-created']


class Follow(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='follower'
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='following'
    )

posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['group', 'text', 'image', ]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text', ]

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("first_name", "last_name", "username", "email")

posts/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from .models import Post, Group, User, Follow
from .forms import PostForm, CommentForm


def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'index.html', {
        'page': page,
    })


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'group.html', {
        'group': group,
        'posts': posts,
        'page': page,
    })


@login_required
def new_post(request):
    form = PostForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            form.save()
            return redirect('posts:index')
    return render(request, 'new.html', {'form': form})


def profile(request, username):
    author = get_object_or_404(User, username=username)
    following = request.user.is_authenticated and Follow.objects.filter(
        author=author,
        user=request.user
    ).exists()
    posts = author.posts.all()
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        'page': page,
        'author': author,
        'following': following,
        'posts': posts,
    }
    return render(request, 'profile.html', context)


def post_view(request, username, post_id):
    post = get_object_or_404(Post, pk=post_id, author__username=username)
    author = post.author
    form = CommentForm()
    comments = post.comments.all()
    return render(
        request,
        'post_view.html',
        {'post': post,
         'author': author,
         'comments': comments,
         'form': form,
         }
    )


@login_required
def post_edit(request, username, post_id):
    post = get_object_or_404(Post, author__username=username, id=post_id)
    if post.author != request.user:
        return redirect('posts:post_view', username=username, post_id=post_id)
    form = PostForm(
        instance=post, files=request.FILES or None, data=request.POST or None
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_view', username=username, post_id=post_id)
    return render(request, 'post_edit.html', {'form': form, 'post': post})


@login_required
def add_comment(request, username, post_id):
    post = get_object_or_404(Post, author__username=username, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_view', username=username, post_id=post_id)


@login_required
def follow_index(request):
    user = request.user
    post = Post.objects.filter(author__following__user=user)
    paginator = Paginator(post, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'follow.html', {
        'page': page,
        'user': user,
    })


@login_required
def profile_follow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    if user != author:
        Follow.objects.get_or_create(
            user=user,
            author=author,
        )
    return redirect(reverse('posts:profile', args=[username]))


@login_required
def profile_unfollow(request, username):
    follow = get_object_or_404(
        Follow, author__username=username, user=request.user)
    follow.delete()
    return redirect(reverse('posts:profile', args=[username]))


def page_not_found(request, exception):
    return render(
        request,
        'misc/404.html',
        {'path': request.path},
        status=404
    )


def server_error(request):
    return render(
        request,
        'misc/500.html',
        status=500
    )

users/views.py
from django.views.generic import CreateView

from django.urls import reverse_lazy

from .forms import CreationForm

from django.contrib.auth.decorators import login_required


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy("signup")
    template_name = "signup.html"


@login_required
def my_view(request):
    ...

users/templates/comments.html
<!-- Форма добавления комментария -->
{% load user_filters %}

{% if user.is_authenticated %}
<div class="card my-4">
    <form method="post" action="{% url 'posts:add_comment' post.author.username post.id %}">
        {% csrf_token %}
        <h5 class="card-header">Добавить комментарий:</h5>
        <div class="card-body">
            <div class="form-group">
                {{ form.text|addclass:"form-control" }}
            </div>
            <button type="submit" class="btn btn-primary">Отправить</button>
        </div>
    </form>
</div>
{% endif %}

<!-- Комментарии -->
{% for item in comments %}
<div class="media card mb-4">
    <div class="media-body card-body">
        <h5 class="mt-0">
            <a href="{% url 'posts:profile' item.author.username %}"
               name="comment_{{ item.id }}">
                {{ item.author.username }}
            </a>
        </h5>
        <p>{{ item.text | linebreaksbr }}</p>
        <small class="text-muted">{{ item.created }}</small>
    </div>
</div>
{% endfor %}

users/templates/follow.html
{% extends "base.html" %}
{% block title %} Последние обновления у авторов {% endblock %}

{% block content %}
    <div class="container">
        {% include "menu.html" with follow=True %}
           <h1> Последние обновления на сайте</h1>
           {% load cache %}
           {% cache 20 index_page page %}
            <!-- Вывод ленты записей -->
                {% for post in page %}
                  <!-- Вот он, новый include! -->
                    {% include "post_item.html" with post=post %}
                {% endfor %}
           {% endcache %}
    </div>

        <!-- Вывод паджинатора -->
        {% if page.has_other_pages %}
            {% include "paginator.html" with items=page paginator=paginator%}
        {% endif %}

{% endblock %}

users/templates/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <p class="m-0 text-dark text-center "><a href="{% url 'about:author' %}">Об авторе</a></p>
    <p class="m-0 text-dark text-center "><a href="{% url 'about:tech' %}">Технологии</a></p>
    <p class="m-0 text-dark text-center ">Социальная сеть <span style="color:red">Ya</span>tube © 2021, все права защищены.</p>
</footer>

users/templates/menu.html
{% if user.is_authenticated %} 
<div class="row">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link {% if index %}active{% endif %}" href="{% url 'posts:index' %}">
                  Все авторы
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if follow %}active{% endif %}" href="{% url 'posts:follow_index' %}">
                Избранные авторы
            </a>
        </li>
    </ul>
</div>
{% endif %}

users/templates/nav.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="/"><span style="color:red">Ya</span>tube</a>
    <nav class="my-2 my-md-0 mr-md-3">
        {% if user.is_authenticated %}
        Пользователь: <a class="header_lincs_post" href="{% url 'posts:profile' user.username %}">{{ user.username }}</a>
        <a class="p-2 text-dark" href="{% url 'posts:new_post' %}">Новая запись</a>
        <a class="p-2 text-dark" href="{% url 'password_change' %}">Изменить пароль</a>
        <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
        {% else %}
        <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
        <a class="p-2 text-dark" href="{% url 'signup' %}">Регистрация</a>
        {% endif %}
    </nav>
</nav>

users/templates/new.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}{% endblock %} | Yatube</title>
        <!-- Загрузка статики -->
        {% load static %}
        <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
        <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
        <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
    </head>
    <body>
        {% include 'nav.html' %}
        <main>
            <div class="container">
                {% block content %}
                 <form method="post" enctype="multipart/form-data">
                   {% csrf_token %}
                   {{ form.as_p }}
                  <input type="submit" value="Отправить">
                 </form>
                {% endblock content %}
            </div>
        </main>
    </body>
</html>

users/templates/post_edit.html
{% extends "base.html" %}
{% block title %}Редактировать запись{% endblock %}
{% block content %}
{# загружаем фильтр #}
{% load user_filters %}

<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">Редактировать запись</div>
            <div class="card-body">

              {% for error in form.errors %}
                  <div class="alert alert-danger" role="alert">
                      {{ error|escape }}
                  </div>
                {% endfor %}

                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                                <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                                <div class="col-md-6">

                                    {# подключаем фильтр и указываем класс #}
                                    {{ field|addclass:"form-control" }}

                                    {% if field.help_text %}
                                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                                    {% endif %}
                                </div>
                        </div>
                    {% endfor %}

                    <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">
                                Сохранить
                            </button>
                    </div>
                </form>
            </div> <!-- card body -->
        </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->

{% endblock %}  

users/templates/post_item.html
<div class="card mb-3 mt-1 shadow-sm">

    <!-- Отображение картинки -->
  {% load thumbnail %}
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
  <img class="card-img" src="{{ im.url }}" />
  {% endthumbnail %}

    <!-- Отображение текста поста -->
    <div class="card-body">
      <p class="card-text">

        <!-- Ссылка на автора через @ -->
        <a name="post_{{ post.id }}" href="{% url 'posts:profile' post.author.username %}">
          <strong class="d-block text-gray-dark">@{{ post.author }}</strong>
        </a>
        {{ post.text|linebreaksbr }}
      </p>

      <!-- Если пост относится к какому-нибудь сообществу, то отобразим ссылку на него через # -->
      {% if post.group %}
      <a class="card-link muted" href="{% url 'posts:group_posts' post.group.slug %}">
        <strong class="d-block text-gray-dark">#{{ post.group.title }}</strong>
      </a>
      {% endif %}

      <!-- Отображение ссылки на комментарии -->
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          {% if post.comments.exists %}
          <div>
            Комментариев: {{ post.comments.count }}
            &nbsp;
          </div>
          {% endif %}

          <a class="btn btn-sm btn-primary" href="{% url 'posts:post_view' post.author.username post.id %}" role="button">
            Добавить комментарий
          </a>

          <!-- Ссылка на редактирование поста для автора -->
          {% if user == post.author %}
          <a class="btn btn-sm btn-info" href="{% url 'posts:post_edit' post.author.username post.id %}" role="button">
            Редактировать
          </a>
          {% endif %}
        </div>

        <!-- Дата публикации поста -->
        <small class="text-muted">{{ post.pub_date }}</small>
      </div>
    </div>
  </div>

users/templates/post_view.html
{% extends "base.html" %}
{% block header %}Страница поста{% endblock %}
{% block content %}
<main role="main" class="container">
    <div class="row">
            <div class="col-md-3 mb-3 mt-1">
                <div class="card">
                        <div class="card-body">
                                <div class="h2">
                                    <!-- Имя автора -->
                                    {{ author.get_full_name }}
                                </div>
                                <div class="h3 text-muted">
                                     <!-- username автора -->
                                     {{ author }}
                                </div>
                        </div>
                        <ul class="list-group list-group-flush">
                                <li class="list-group-item">
                                        <div class="h6 text-muted">
                                        Подписчиков: {{ author.following.count }} <br />
                                        Подписан: {{ author.follower.count }}
                                        </div>
                                </li>
                                <li class="list-group-item">
                                        <div class="h6 text-muted">
                                            <!--Количество записей -->
                                            Записей: {{ page.paginator.count }}
                                        </div>
                                </li>
                        </ul>
                </div>
        </div>
        <div class="col-md-9">
              <!-- Вот он, новый include! -->
              {% include "post_item.html" with post=post %}
              {% include "comments.html" %}
        </div>
    </div>
</main>
{% endblock %}

users/templates/profile.html
{% extends "base.html" %}


{% block content %}
    <div class="container">
           <h1> Страница пользователя </h1>

           <div class="row">
                <div class="col-md-3 mb-3 mt-1">
                        <div class="card">
                                <div class="card-body">
                                        <div class="h2">
                                            <!-- Имя автора -->
                                            {{ author.get_full_name }}
                                        </div>
                                        <div class="h3 text-muted">
                                             <!-- username автора -->
                                             @{{ author }}
                                        </div>
                                </div>
                                <ul class="list-group list-group-flush">
                                        <li class="list-group-item">
                                                <div class="h6 text-muted">
                                                Подписчиков: {{ author.following.count }} <br />
                                                Подписан: {{ author.follower.count }}
                                                </div>
                                        </li>
                                        <li class="list-group-item">
                                                <div class="h6 text-muted">
                                                    <!-- Количество записей -->
                                                    Записей: {{ page.paginator.count }}
                                                </div>
                                        </li>
                                        <li class="list-group-item">
                                            {% if following %}
                                                <a class="btn btn-lg btn-light"
                                                        href="{% url 'posts:profile_unfollow' author.username %}" role="button">
                                                        Отписаться
                                                </a>
                                            {% else %}
                                                <a class="btn btn-lg btn-primary"
                                                        href="{% url 'posts:profile_follow' author.username %}" role="button">
                                                        Подписаться
                                                </a>
                                            {% endif %}
                                        </li>
                                </ul>
                        </div>
                </div>

                <div class="col-md-9">
            <!-- Вывод ленты записей -->
            {% for post in page %}
            <!-- Вот он, новый include! -->
              {% include "post_item.html" with post=post %}
            {% endfor %}
                </div>

         <!-- Вывод паджинатора -->
         {% if page.has_other_pages %}
         {% include "paginator.html" with items=page paginator=paginator%}
         {% endif %}
           </div>
    </div>
{% endblock %}

users/templates/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
{# загружаем фильтр #}
{% load user_filters %}

<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">Зарегистрироваться</div>
            <div class="card-body">

              {% for error in form.errors %}
                  <div class="alert alert-danger" role="alert">
                      {{ error|escape }}
                  </div>
                {% endfor %}

                <form method="post" action="{% url 'signup' %}">
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                                <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                                <div class="col-md-6">

                                    {# подключаем фильтр и указываем класс #}
                                    {{ field|addclass:"form-control" }}

                                    {% if field.help_text %}
                                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                                    {% endif %}
                                </div>
                        </div>
                    {% endfor %}

                    <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">
                                Зарегистрироваться
                            </button>
                    </div>
                </form>
            </div> <!-- card body -->
        </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->

{% endblock %}